### ISSUE TITLE
Crash on startup with ExtraBiomesXL

### ISSUE THREAD

**Issue by Stormwind99** [TheWeatherPony/TheSeasonsMod#101]
Versions:
- Minecraft 1.7.10
- forge-10.13.4.1614
- [1.7.10]TheSeasonsMod-pre-3.0beta13d5
- extrabiomesxl_1.7.10-3.16.4

Call stack:

```
---- Minecraft Crash Report ----
// Don't do that.

Time: 2/4/17 10:19 PM
Description: Initializing game

java.lang.IllegalAccessError: tried to access class extrabiomes.module.cautia.block.BlockQuicksand from class weatherpony.partial.generated.extrabiomes.module.cautia.block.BlockQuicksand.proxyNum0
	at weatherpony.partial.generated.extrabiomes.module.cautia.block.BlockQuicksand.proxyNum0.call2(Unknown Source)
	at weatherpony.partial.generated.extrabiomes.module.cautia.block.BlockQuicksand.proxyNum0.call2(Unknown Source)
	at weatherpony.partial.CallWrapper.call(CallWrapper.java:52)
	at weatherpony.partial.HookListenerHelper.callProxy(HookListenerHelper.java:85)
	at weatherpony.partial.HookListenerHelper.callNext(HookListenerHelper.java:71)
	at weatherpony.seasons.pml.edits.texturefixes.TextureRetrivalDuringCreation$RegisterBlockIcons.call2(TextureRetrivalDuringCreation.java:37)
	at weatherpony.seasons.pml.edits.texturefixes.TextureRetrivalDuringCreation$RegisterBlockIcons.call2(TextureRetrivalDuringCreation.java:21)
	at weatherpony.partial.CallWrapper.call(CallWrapper.java:52)
	at weatherpony.partial.HookListenerHelper.callNext(HookListenerHelper.java:75)
	at weatherpony.partial.HookListenerHelper.distribute(HookListenerHelper.java:64)
	at weatherpony.partial.HookListenerHelperPool.distribute(HookListenerHelperPool.java:134)
	at weatherpony.partial.internal.GeneralHookManager.rigAndDistributeCall(GeneralHookManager.java:276)
	at extrabiomes.module.cautia.block.BlockQuicksand.func_149651_a(BlockQuicksand.java)
	at net.minecraft.client.renderer.texture.TextureMap.func_110573_f(TextureMap.java:335)
	at net.minecraft.client.renderer.texture.TextureMap.<init>(TextureMap.java:62)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:540)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at weatherpony.pml.premain.ReplacementMainThread.run(ReplacementMainThread.java:104)
```

**Comment by jredfox** [comment]
use https://pastebin.com next time for crashes

**Comment by jredfox** [comment]
why is this mod asking for the class access. You shouldn't need it with forge. You simply populate your array list of biome properties in post init and then if the biome != null get it's properties

**Comment by TheWeatherPony** [comment]
Update to the new build of PML for the fix.
jredfox, it's because of part of the Java language. And it's not accessing a biome, it's trying to access a section of executable code that it "shouldn't be able to" belonging to that biome's class.

**Comment by jredfox** [comment]
Ok I was just thinking that you had your code to look for the biomes before postinit begins with forge. Which would mean they would have a potability for unregistered biomes.
